#ifndef __PORTABLE_H__
#define __PORTABLE_H__

#include <sys/ptrace.h>

#define __FREEBSD__ 0

#if __FREEBSD__ 			/* Just for BSD */

#define PTRACE_TRACEME PT_TRACE_ME
#define PTRACE_PEEKTEXT PT_READ_I
#define PTRACE_PEEKDATA PT_READ_D
#define PTRACE_PEEKUSER PT_READ_U
#define PTRACE_POKETEXT PT_WRITE_I
#define PTRACE_POKEDATA PT_WRITE_D
#define PTRACE_POKEUSER PT_WRITE_U
#define PTRACE_CONT PT_CONTINUE
#define PTRACE_KILL PT_KILL
#define PTRACE_SINGLESTEP PT_STEP
#define PTRACE_GETREGS PT_GETREGS
#define PTRACE_SETREGS PT_SETREGS
#define PTRACE_GETFPREGS PT_GETFPREGS
#define PTRACE_SETFPREGS PT_SETFPREGS
#define PTRACE_ATTACH PT_ATTACH
#define PTRACE_DETACH PT_DETACH
#define PTRACE_GETFPXREGS PT_GETFPXREGS
#define PTRACE_SETFPXREGS PT_SETFPXREGS
#define PTRACE_SYSCALL PT_SYSCALL
#define PTRACE_SETOPTIONS PT_SETOPTIONS
#define PTRACE_GETEVENTMSG PT_GETEVENTMSG
#define PTRACE_GETSIGINFO PT_GETSIGINFO
#define PTRACE_SETSIGINFO PT_SETSIGINFO


#else 			/* For linux */

#define PT_TRACE_ME PTRACE_TRACEME
#define PT_READ_I PTRACE_PEEKTEXT
#define PT_READ_D PTRACE_PEEKDATA
#define PT_READ_U PTRACE_PEEKUSER
#define PT_WRITE_I PTRACE_POKETEXT
#define PT_WRITE_D PTRACE_POKEDATA
#define PT_WRITE_U PTRACE_POKEUSER
#define PT_CONTINUE PTRACE_CONT
#define PT_KILL PTRACE_KILL
#define PT_STEP PTRACE_SINGLESTEP
#define PT_GETREGS PTRACE_GETREGS
#define PT_SETREGS PTRACE_SETREGS
#define PT_GETFPREGS PTRACE_GETFPREGS
#define PT_SETFPREGS PTRACE_SETFPREGS
#define PT_ATTACH PTRACE_ATTACH
#define PT_DETACH PTRACE_DETACH
#define PT_GETFPXREGS PTRACE_GETFPXREGS
#define PT_SETFPXREGS PTRACE_SETFPXREGS
#define PT_SYSCALL PTRACE_SYSCALL
#define PT_SETOPTIONS PTRACE_SETOPTIONS
#define PT_GETEVENTMSG PTRACE_GETEVENTMSG
#define PT_GETSIGINFO PTRACE_GETSIGINFO
#define PT_SETSIGINFO PTRACE_SETSIGINFO
	

#endif


#endif
